foreach(IMAGECPP_REQUIRED_VARIABLE IMAGECPP_MODEL_OUTPUT IMAGECPP_MODEL_URL IMAGECPP_MODEL_SHA256 IMAGECPP_MODEL_NAME)
    if(NOT DEFINED ${IMAGECPP_REQUIRED_VARIABLE} OR "${${IMAGECPP_REQUIRED_VARIABLE}}" STREQUAL "")
        message(FATAL_ERROR "${IMAGECPP_REQUIRED_VARIABLE} is required")
    endif()
endforeach()

get_filename_component(IMAGECPP_MODEL_DIRECTORY "${IMAGECPP_MODEL_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${IMAGECPP_MODEL_DIRECTORY}")

if(EXISTS "${IMAGECPP_MODEL_OUTPUT}")
    file(SHA256 "${IMAGECPP_MODEL_OUTPUT}" IMAGECPP_EXISTING_SHA256)
    if(IMAGECPP_EXISTING_SHA256 STREQUAL IMAGECPP_MODEL_SHA256)
        message(STATUS "${IMAGECPP_MODEL_NAME} ready: ${IMAGECPP_MODEL_OUTPUT}")
        return()
    endif()
    message(STATUS "${IMAGECPP_MODEL_NAME} checksum mismatch; downloading a verified replacement")
endif()

set(IMAGECPP_MODEL_TEMPORARY "${IMAGECPP_MODEL_OUTPUT}.download")
file(DOWNLOAD
    "${IMAGECPP_MODEL_URL}"
    "${IMAGECPP_MODEL_TEMPORARY}"
    EXPECTED_HASH "SHA256=${IMAGECPP_MODEL_SHA256}"
    SHOW_PROGRESS
    STATUS IMAGECPP_DOWNLOAD_STATUS
    TLS_VERIFY ON
)
list(GET IMAGECPP_DOWNLOAD_STATUS 0 IMAGECPP_DOWNLOAD_CODE)
list(GET IMAGECPP_DOWNLOAD_STATUS 1 IMAGECPP_DOWNLOAD_MESSAGE)
if(NOT IMAGECPP_DOWNLOAD_CODE EQUAL 0)
    file(REMOVE "${IMAGECPP_MODEL_TEMPORARY}")
    message(FATAL_ERROR "${IMAGECPP_MODEL_NAME} download failed: ${IMAGECPP_DOWNLOAD_MESSAGE}")
endif()

file(REMOVE "${IMAGECPP_MODEL_OUTPUT}")
file(RENAME "${IMAGECPP_MODEL_TEMPORARY}" "${IMAGECPP_MODEL_OUTPUT}")
message(STATUS "${IMAGECPP_MODEL_NAME} ready: ${IMAGECPP_MODEL_OUTPUT}")
