if(NOT DEFINED IMAGECPP_MODEL_OUTPUT OR IMAGECPP_MODEL_OUTPUT STREQUAL "")
    message(FATAL_ERROR "IMAGECPP_MODEL_OUTPUT is required")
endif()

get_filename_component(IMAGECPP_MODEL_DIRECTORY "${IMAGECPP_MODEL_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${IMAGECPP_MODEL_DIRECTORY}")

set(IMAGECPP_MODEL_TEMPORARY "${IMAGECPP_MODEL_OUTPUT}.download")
file(DOWNLOAD
    "https://huggingface.co/PABannier/sam3.cpp/resolve/main/edgetam_q4_0.ggml"
    "${IMAGECPP_MODEL_TEMPORARY}"
    EXPECTED_HASH SHA256=a8a35e35fb9a1b6f099c3f35e3024548b0fc979c2a4184642562804192496e09
    SHOW_PROGRESS
    STATUS IMAGECPP_DOWNLOAD_STATUS
    TLS_VERIFY ON
)
list(GET IMAGECPP_DOWNLOAD_STATUS 0 IMAGECPP_DOWNLOAD_CODE)
list(GET IMAGECPP_DOWNLOAD_STATUS 1 IMAGECPP_DOWNLOAD_MESSAGE)
if(NOT IMAGECPP_DOWNLOAD_CODE EQUAL 0)
    file(REMOVE "${IMAGECPP_MODEL_TEMPORARY}")
    message(FATAL_ERROR "EdgeTAM download failed: ${IMAGECPP_DOWNLOAD_MESSAGE}")
endif()

file(RENAME "${IMAGECPP_MODEL_TEMPORARY}" "${IMAGECPP_MODEL_OUTPUT}")
message(STATUS "EdgeTAM model ready: ${IMAGECPP_MODEL_OUTPUT}")
