if(NOT DEFINED IMAGECPP_INSTALL_PREFIX OR IMAGECPP_INSTALL_PREFIX STREQUAL "")
    message(FATAL_ERROR "IMAGECPP_INSTALL_PREFIX must name the image.cpp install prefix")
endif()

set(IMAGECPP_INSTALLED_CLI "${IMAGECPP_INSTALL_PREFIX}/bin/imagecpp")
if(WIN32)
    string(APPEND IMAGECPP_INSTALLED_CLI ".exe")
endif()

execute_process(
    COMMAND "${IMAGECPP_INSTALLED_CLI}" inspect
    RESULT_VARIABLE IMAGECPP_INSTALLED_CLI_RESULT
    OUTPUT_VARIABLE IMAGECPP_INSTALLED_CLI_OUTPUT
    ERROR_VARIABLE IMAGECPP_INSTALLED_CLI_ERROR
)
if(NOT IMAGECPP_INSTALLED_CLI_RESULT EQUAL 0)
    message(FATAL_ERROR
        "Installed imagecpp CLI failed with ${IMAGECPP_INSTALLED_CLI_RESULT}\n"
        "stdout:\n${IMAGECPP_INSTALLED_CLI_OUTPUT}\n"
        "stderr:\n${IMAGECPP_INSTALLED_CLI_ERROR}"
    )
endif()
